# Generated by Django 6.1.1 on 2026-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conference',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
