# Generated by Django 6.1.1 on 2026-10-03 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conference_title_alter_conference_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='word_file',
        ),
        migrations.CreateModel(
            name='WordPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maqola_soni', models.IntegerField()),
                ('bet_soni', models.IntegerField()),
                ('yaratilgan_sana', models.DateField(auto_now_add=True)),
                ('word_fayl', models.FileField(upload_to='word_files/')),
                ('content', models.TextField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_parts', to='api.conference')),
            ],
        ),
    ]
