# Generated by Django 6.1.1 on 2026-10-03 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_conference_word_file_wordpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('yaratilgan_sana', models.DateField(auto_now_add=True)),
                ('word_fayl', models.FileField(upload_to='word_files/')),
                ('shoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maqola', to='api.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Shoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='imgs/')),
                ('is_active', models.BooleanField(default=False)),
                ('yaratilgan_sana', models.DateField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoba', to='api.conference')),
            ],
        ),
    ]
