# Generated by Django 6.1.1 on 2026-10-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_maqola_shoba'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutShoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('maqala_soni', models.IntegerField()),
                ('yaratilgan_sana', models.DateField(auto_now_add=True)),
                ('shobaxaqida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoba_malumot', to='api.conference')),
            ],
        ),
    ]
