# Generated by Django 6.1.1 on 2026-10-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aboutshoba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutshoba',
            name='maqala_soni',
        ),
        migrations.RemoveField(
            model_name='aboutshoba',
            name='shobaxaqida',
        ),
        migrations.AddField(
            model_name='aboutshoba',
            name='maqola_soni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutshoba',
            name='shoba',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='api.shoba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutshoba',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='shoba',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aboutshoba',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='shoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maqolalar', to='api.shoba'),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoba',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shobalar', to='api.conference'),
        ),
        migrations.AlterField(
            model_name='shoba',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
