# Generated by Django 6.1.1 on 2026-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_aboutshoba_maqala_soni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpart',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
