# Generated by Django 6.1.1 on 2026-10-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_wordpart_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutshoba',
            name='yaratilgan_sana',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shoba',
            name='yaratilgan_sana',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AboutMaqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muallif', models.CharField(max_length=255)),
                ('shoba', models.CharField(max_length=255)),
                ('konfrensiya', models.TextField()),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilanish', models.DateTimeField(auto_now=True)),
                ('umumiy_word', models.IntegerField(default=0)),
                ('word_fayl', models.FileField(upload_to='word_files/')),
                ('maqola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutmaqolalar', to='api.maqola')),
            ],
        ),
    ]
