# Generated by Django 6.1.1 on 2026-10-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_maqola_type_alter_aboutshoba_yaratilgan_sana_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMaqola',
        ),
    ]
