# Generated by Django 6.1.1 on 2026-10-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_aboutmaqola'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMaqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muallif', models.CharField(max_length=255)),
                ('konfrensiya', models.TextField()),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilanish', models.DateTimeField(auto_now=True)),
                ('word_bet', models.IntegerField(default=0)),
                ('word_fayl', models.FileField(upload_to='word_files/')),
                ('maqola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_maqolalar', to='api.maqola')),
            ],
        ),
    ]
