# Generated by Django 6.1.1 on 2026-10-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_aboutmaqola'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmaqola',
            name='shoba',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='about_shoba', to='api.shoba'),
            preserve_default=False,
        ),
    ]
