# Generated by Django 6.1.1 on 2026-10-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_aboutmaqola_shoba'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoba',
            name='maqola_soni',
            field=models.IntegerField(default=0),
        ),
    ]
