# Generated by Django 6.1.1 on 2026-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_shoba_maqola_soni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqola',
            old_name='content',
            new_name='konferensiya',
        ),
        migrations.RenameField(
            model_name='maqola',
            old_name='type',
            new_name='muallif',
        ),
        migrations.RemoveField(
            model_name='aboutmaqola',
            name='shoba',
        ),
        migrations.AddField(
            model_name='maqola',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='word_bet',
            field=models.IntegerField(default=0),
        ),
    ]
