# Generated by Django 6.1.1 on 2026-10-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_content_maqola_konferensiya_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqola',
            old_name='konferensiya',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='maqola',
            name='muallif',
        ),
    ]
