# Generated by Django 6.1.1 on 2026-10-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_konferensiya_maqola_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmaqola',
            name='konfrensiya',
        ),
    ]
