# Generated by Django 6.1.1 on 2026-10-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
